apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-challenge
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: pet-challenge
  template:
    metadata:
      labels:
        app: pet-challenge
    spec:
      containers:
        - name: pet-challenge
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.containerPort }}
          envFrom:
            - configMapRef:
                name: pet-challenge-config
          readinessProbe:
            httpGet:
              path: {{ .Values.app.probes.readiness.path }}
              port: {{ .Values.app.containerPort }}
            initialDelaySeconds: {{ .Values.app.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.app.probes.liveness.path }}
              port: {{ .Values.app.containerPort }}
            initialDelaySeconds: {{ .Values.app.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.liveness.periodSeconds }}
---
apiVersion: v1
kind: Service
metadata:
  name: pet-challenge
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.app.service.type }}
  selector:
    app: pet-challenge
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.containerPort }}
      nodePort: {{ .Values.app.service.nodePort }}
